accounts/urls.py
from django.urls import path
from accounts import views
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('signup', views.signupuser, name='signupuser'),
    path('profile', views.profile, name='profile'),
    path('logout', views.logoutuser, name='logoutuser'),
    path('login', views.loginuser, name='loginuser'),
    path('events', views.events, name='events'),
    path('cat', views.cat, name='cat'),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

work_1_project/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.DateField()
    time = models.TimeField()
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    is_public = models.BooleanField(default=True)

class AvatarProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField(upload_to='profile_pictures/')

accounts/forms.py
# forms.py
from django import forms
from .models import Event, AvatarProfile

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['title', 'description', 'date', 'time', 'is_public']
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Введите название события'}),
            'description': forms.Textarea(attrs={'placeholder': 'Что нового?'}),
            'date': forms.DateInput(attrs={'type': 'date'}),
            'time': forms.TimeInput(attrs={'type': 'time'}),
            'is_public': forms.CheckboxInput(attrs={'class': 'custom-checkbox'}),
        }

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = AvatarProfile
        fields = ['profile_picture']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db.utils import IntegrityError
from django.contrib.auth import login, logout, authenticate
from .forms import EventForm, UserProfileForm
from .models import Event, AvatarProfile

 

# Create your views here.


def signupuser(r):
    if r.method == 'GET':
        return render (r, 'register.html', {'form':UserCreationForm()})
    else:
        if r.POST['password1'] == r.POST['password2']:
            try:
                user = User.objects.create_user(username=r.POST['username'], password=r.POST['password1'])
                user.save()
                login(r, user)
                return  redirect('profile')
            except IntegrityError:
                return render (r,'register.html', {'form':UserCreationForm(), 'error':'Пользователь с таким именем уже существует!'})
        else:
            return render (r, 'register.html', {'form':UserCreationForm(), 'error':'Пароли не совпадают!'})



def profile(r):
    if r.method == 'POST':
        print(r.POST)
        form = EventForm(r.POST)
        if form.is_valid():
            event = form.save(commit=False)
            event.creator = r.user
            event.save()
            return redirect('events')
    else:
        form = EventForm()
    return render(r, 'profile.html', {'form': form})

def events(request):
    events = Event.objects.filter(is_public=True)
    return render(request, 'event_list.html', {'events': events})

def logoutuser(r):
    if r.method == 'POST':
        logout(r)
        return redirect('home')

def loginuser(r):
    if r.method == 'GET':
        return render (r, 'loginuser.html', {'form':AuthenticationForm()})
    else:
        user = authenticate(r, username=r.POST['username'], password=r.POST['password'])
        if user is None:
            return render (r, 'loginuser.html', {'form':AuthenticationForm(), 'error':'Неверный логин или пароль!'}) 
        else:
            login(r, user)
            return redirect('profile')
        

def cat(request):
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES)
        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()
            return redirect('profile')  # Перенаправьте пользователя на страницу профиля
    else:
        form = UserProfileForm()
    
    # Получите профиль пользователя, чтобы отобразить его фотографию
    try:
        user_profile = AvatarProfile.objects.get(user=request.user)
        return render(request, 'upload_profile_picture.html', {'form': form, 'user_profile': user_profile})
    except:
        return render(request, 'upload_profile_picture.html', {'form': form, 'user_profile': 'Фото нету'})

    

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
# from .forms import PostForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.db.utils import IntegrityError
from django.contrib.auth.models import User
from django.http import JsonResponse
# приветик


# Create your views here.
def home(r):
    if r.method == 'GET':
        return render (r, 'index.html', {'form_reg':UserCreationForm(), 'form_log':AuthenticationForm})
    else:
        try:
            user = authenticate(r, username=r.POST['username'], password=r.POST['password'])
            if user is None:
                return render (r, 'loginuser.html', {'form':AuthenticationForm(), 'error':'Неверный логин или пароль!'}) 
            else:
                login(r, user)
                return redirect('profile')
        except:
            if r.POST['password1'] == r.POST['password2']:
                try:
                    user = User.objects.create_user(username=r.POST['username'], password=r.POST['password1'])
                    user.save()
                    login(r, user)
                    return  redirect('profile')
                except IntegrityError:
                        return render (r,'register.html', {'form_reg':UserCreationForm(), 'form_log':AuthenticationForm,  'error':'Пользователь с таким именем уже существует!'})
            else:
                return render (r, 'register.html', {'form_reg':UserCreationForm(), 'form_log':AuthenticationForm, 'error':'Пароли не совпадают!'})

accounts/templates/event_list.html
<html>
<head>
    <title>Event List</title>
</head>
<body>
    <h1>Event List</h1>
    <ul>
        {% for event in events %}
            {{ event.title }} - {{ event.date }}
            {{ event.description }} <br><br>
           
        {% endfor %}
    </ul>
</body>
</html>

accounts/templates/loginuser.html
<h1>Вход</h1>

<h2>{{ error }}</h2>

<form method="POST">
    {% csrf_token %}
{{ form.as_p }}
<button type="submit">
    Войти
</button>
</form>

accounts/templates/profile.html
{% load static %}
{% if user.is_authenticated %}

<html>
<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SocialWeb</title>

    <!-- Bootstrap reboot (для сброса стилей) -->
    <link rel="stylesheet" href="{% static 'bootstrap-reboot.min.css' %}">

    <!-- Bootstrap сетка -->
    <link rel="stylesheet" href="{% static 'bootstrap-grid.min.css' %}">

    <!-- Шрифты с Google Fonts -->
    <link rel="preconnect" href="{% static 'https://fonts.gstatic.com' %}">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">

    <!-- Стили сайта -->
    <link rel="stylesheet" href="{% static 'stylessocial.css' %}">
    <!-- Скрипты сайта -->
    <script src="{% static 'jquery-3.7.0.min.js' %}"></script>
    <script src="{% static 'scriptsocial.js' %}"></script>
<head>
    <title>Создать событие</title>
</head>
<body>
    <div class="create-wrap">
        <div class="create-post">
            <h1>Создать событие</h1>
            <form method="POST" >
                {% csrf_token %}
                <div class="form">
                    <div id="id_title" placeholder="Введите название события" >{{ form.title }}</div>
                    <div id="id_description" >{{ form.description }}</div>
                    <div id="id_date" >{{ form.date }}</div>
                    <div id="id_time" >{{ form.time }}</div>
                    <div id="id_is_public" >{{ form.is_public }}</div>
                    <button class="submit-form" type="submit">Создать</button>
                </div>
            </form>
        </div> 
    </div>
</body>
</html>

{% else %}

Пожалуйста, выполните вход

{% endif %}

accounts/templates/register.html
{{ form.as_p }}
<!-- {% block content %}
{% load static %}
    <div class="register-error">
        <h1>Регистрация</h1>

        <h2>{{ error }}</h2>

        <form method="POST">
            {% csrf_token %}
        <div class="username">{{ form.username }}</div>
        {{ form.password1 }}
        {{ form.password2 }}
        <button type="submit">
            Зарегистрироваться
        </button>
        </form>
    </div>
    

{% endblock %} -->

accounts/templates/upload_profile_picture.html
{% if user.is_authenticated and not user_profile.profile_picture.url %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Загрузить</button>
</form>
{% endif %}


{% if not user.is_authenticated %}

Пожалуйста, выполните вход

{% endif %}


{% if user_profile.profile_picture.url %}

<h1>Профиль пользователя</h1>
<img src="{{ user_profile.profile_picture.url }}" alt="Фотография профиля">





{% endif %}

main/templates/html/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>HTML & CSS практика от AVIS TV</title>

	<!-- Bootstrap reboot (для сброса стилей) -->
	<link rel="stylesheet" href="libs/bootstrap-reboot.min.css">

	<!-- Bootstrap сетка -->
	<link rel="stylesheet" href="libs/bootstrap-grid.min.css">

	<!-- Шрифты с Google Fonts -->
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">

	<!-- Стили сайта -->
	<link rel="stylesheet" href="css/styles.css">
	<script src="jquery-3.7.0.min.js"></script>
</head>
<script src="script.js"></script>
<nav class="navbar">
	 	<div class="container">
	 		<a href="#" class="navbar-brand">GEOGAMING</a>
	 		<div class="navbar-wrap">
	 			<ul class="navbar-menu">
	 			<li><a href="#">О нас</a></li>
	 			<li><a href="#">Портфолио</a></li>
	 			<li><a href="#">Цены</a></li>
	 			<li><a href="#">Контакты</a></li>
	 		</ul>
	 		<a href="#" class="callback">Обратный звонок</a>
	 		</div>
	 	</div>
	 </nav>
<body>


	
	
	
	 
</body>
</html>

main/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ru" id="catweb" >
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>catweb.ru</title>
	<!-- Bootstrap reboot (для сброса стилей) -->
	<link rel="stylesheet" href="{% static 'bootstrap-reboot.min.css' %}">

	<!-- Bootstrap сетка -->
	<link rel="stylesheet" href="{% static 'bootstrap-grid.min.css' %}">

	<!-- Шрифты с Google Fonts -->
	<link rel="preconnect" href="{% static 'https://fonts.gstatic.com' %}">
	<link href="{{ 'https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,400;0,700;1,400&display=swap' }}" rel="stylesheet">
	<link rel="stylesheet" href="{{'https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;500;700&display=swap'}}">

	<!-- Стили сайта -->
	<link rel="stylesheet" href="{% static 'style_firstpage.css' %}">
	<!-- Скрипты сайта -->
	
</head>
<body>
	<main>
		<div class="main-content">
			<div class="wrap">
				<div class="image-container" >
					<img class="logo" src="{% static 'Logo-SocialWeb.png' %}">
					<h2 class="logo-title" >Мяукай мысли, мяукай события</h2>
					<img class="cat_logo" src="{% static 'cat_logo.png' %}" >
				</div>
				<div class="login-container">
					<h2>{{ error }}</h2>
					<div class="wrap-form" >
						<form class="sign-up-form" method="POST">
							{% csrf_token %}
						<div class="username">{{ form_log.username }}{{ form_log.password }}</div>
						<button type="submit">Войти</button>
						
						</form>
						<div class="register-btn"><button class="register">Регистрация</button></div>
					</div>
				</div>
			</div>
		</div>
	</main>
	<footer class="footer" >
		<div id="footer">
					<ul class="footer-link">
						<li><a href="#" class="link-footer" >О Нас</a></li>
						<li><a href="#" class="link-footer">Контакты</a></li>
						<li><a href="#" class="link-footer">Разработчикам</a></li>
						<li><a href="#" class="link-footer">Информация</a></li>
						<li><a href="#" class="link-footer">Справка</a></li>
						<li><a href="#" class="link-footer">© 2023 CatWeb</a></li>
					</ul>
		</div>
	</footer>
	
    




</body>
</html>
<!-- ПОКА -->

main/templates/posts.html
<h2>Create a New Post</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Create Post</button>
</form>

main/templates/secondpage.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>SocialWeb</title>

	<!-- Bootstrap reboot (для сброса стилей) -->
	<link rel="stylesheet" href="{% static 'bootstrap-reboot.min.css' %}">

	<!-- Bootstrap сетка -->
	<link rel="stylesheet" href="{% static 'bootstrap-grid.min.css' %}">

	<!-- Шрифты с Google Fonts -->
	<link rel="preconnect" href="{% static 'https://fonts.gstatic.com' %}">
	<link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">

	<!-- Стили сайта -->
	<link rel="stylesheet" href="{% static 'stylessocial.css' %}">
	<!-- Скрипты сайта -->
	<script src="{% static 'jquery-3.7.0.min.js' %}"></script>
	<script src="{% static 'scriptsocial.js' %}"></script>

	
	
</head>
<body>
	
	<!-- Боковое меню -->
	<div class="menu">
		<a href="#" class="menu-btn"></a>
		<nav class="menu-list">
			<a href="#main">Главная</a>
			<a href="#news">Новости</a>
			<a href="#friends">Друзья</a>
			<a href="#photo">Фото</a>
		</nav>
		
		<div class="profile-login">
				<button class="login-btn" id="open-modal-btn-login">Войти</button>
				<button class="sign-up" id="open-modal-btn">Зарегистрироваться</button>
		</div>
	</div>


	
	<!-- Главный контент -->
	<div class="content">
		<section class="main">
			<a id="main">Главная</a>
		</section>
		<section class="news">
			<a id="news">Новости</a>
		</section>
		<section class="friends">
			<a id="friends">Друзья</a>
		</section>
		<section class="photo">
			<a id="photo">Фото</a>
		</section>

	</div>
	<!-- Всплывающее окно с кнопками -->
	<div class="modal" id="my-modal">
			<div class="modal-window"><!-- Всплывающее окно с кнопками РЕГИСТРАЦИЯ -->
				<h1>Регистрация</h1>
				<div>
					<h2>{{ error }}</h2>	
					<form method="POST">
						{% csrf_token %}
					<div class="username">{{ form_reg.username }}</div>
					{{ form_reg.password1 }}
					{{ form_reg.password2 }}
					<button type="submit">Зарегистрироваться</button>
					</form>
				</div>
				<button class="close-modal-btn">X</button>
			</div>
	</div>
	<div class="login" id="my-login">
		<div class="window-login"><!-- Всплывающее окно с кнопками ВХОД -->
				<h1>Вход</h1>
				<div>
					<h2>{{ error }}</h2>	
					<form method="POST">
						{% csrf_token %}
					<div class="username">{{ form_log.username }}</div>
					{{ form_log.password }}
					<button type="submit">Войти</button>
					</form>
				</div>
				<button class="close-modal-btn-login">X</button>
		
	</div>
			
	

</body>
</html>